name: Check

on:
  push:
    branches: [ main ]

  pull_request:
    types: [ opened, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
# ======================================= Run Tests =========================================================




# ======================================= Run Linters =========================================================



  # ======================================= Check Declarations =======================================

  declaration-tester-project-macos:
    name: Declaration Tester Project MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Publish Konsist Artifact To Local Maven Repository
        run: >
          ./gradlew publishToMavenLocal

      - name: Run Integration Test
        run: cd test-projects/konsist-declaration-tester/ && ./gradlew integrationTest

      - name: Upload Report
        if: always() # Ensure the step runs regardless of the outcome of previous steps (failed tests will be uploaded)
        uses: actions/upload-artifact@v4
        with:
          name: declaration-tester-project-macos-test-report
          path: test-projects/konsist-declaration-tester/app/build/reports/integrationTest


# ======================================= Library Artifact =========================================================

# ======================================= Other =========================================================

